on:
  release:
    types:
    - created
    - published

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo -n '${{ github.ref }}' | sed 's|refs/tags/||' > ./target/TAG_NAME
    - name: Docker Build & Push to Docker Hub
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        USERNAME: '${{ secrets.DOCKER_USER }}'
        PASSWORD: '${{ secrets.DOCKER_TOKEN }}'
        DOCKERFILE: Dockerfile
        LATEST: 'false'
